# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - edu-chatbot-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d011cab63ef9495587dfe59ccd5c1c9a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_14dbe9c7d2c34187ab6269ce462890b4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d011cab63ef9495587dfe59ccd5c1c9a }}/edu-chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'edu-chatbot-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6102d900461345bd9b54a5b8b289d1f1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d011cab63ef9495587dfe59ccd5c1c9a }}/edu-chatbot:${{ github.sha }}'